import type { Metadata } from "next"
import { BarChart, Search, AlertTriangle, Clock, Shield, CheckCircle, Database, FileText, Lock } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import Link from "next/link"

export const metadata: Metadata = {
  title: "SIEM Solutions | Supreme Information Security LLC",
  description:
    "Advanced Security Information and Event Management (SIEM) solutions for comprehensive threat detection, compliance, and incident response.",
}

export default function SiemPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      {/* Hero Section */}
      <div className="text-center mb-16">
        <h1 className="text-4xl md:text-5xl font-bold mb-6">SIEM Solutions</h1>
        <p className="text-xl text-gray-600 max-w-3xl mx-auto">
          Our Security Information and Event Management (SIEM) solutions provide real-time analysis of security alerts
          generated by applications and network hardware across your entire infrastructure.
        </p>
      </div>

      {/* Key Features */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
        <Card className="border-l-4 border-l-red-600">
          <CardContent className="pt-6">
            <div className="flex items-start gap-4">
              <div className="bg-red-100 p-3 rounded-full">
                <Search className="h-6 w-6 text-red-600" />
              </div>
              <div>
                <h3 className="text-xl font-bold mb-2">Threat Detection</h3>
                <p className="text-gray-600">
                  Advanced analytics to identify known and unknown threats across your environment.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-l-4 border-l-red-600">
          <CardContent className="pt-6">
            <div className="flex items-start gap-4">
              <div className="bg-red-100 p-3 rounded-full">
                <BarChart className="h-6 w-6 text-red-600" />
              </div>
              <div>
                <h3 className="text-xl font-bold mb-2">Log Management</h3>
                <p className="text-gray-600">
                  Centralized collection and analysis of logs from across your IT infrastructure.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-l-4 border-l-red-600">
          <CardContent className="pt-6">
            <div className="flex items-start gap-4">
              <div className="bg-red-100 p-3 rounded-full">
                <AlertTriangle className="h-6 w-6 text-red-600" />
              </div>
              <div>
                <h3 className="text-xl font-bold mb-2">Incident Response</h3>
                <p className="text-gray-600">
                  Automated alerting and response workflows to address security incidents quickly.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Solution Components */}
      <div className="mb-16">
        <h2 className="text-3xl font-bold mb-8 text-center">Comprehensive SIEM Capabilities</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {[
            {
              title: "Real-time Monitoring",
              description:
                "Continuous monitoring of security events across your network, endpoints, applications, and cloud environments.",
              icon: <Clock className="h-6 w-6 text-red-600" />,
            },
            {
              title: "Security Analytics",
              description:
                "Advanced analytics using machine learning and behavioral analysis to detect sophisticated threats.",
              icon: <BarChart className="h-6 w-6 text-red-600" />,
            },
            {
              title: "Compliance Reporting",
              description:
                "Automated reporting for regulatory compliance requirements such as PCI DSS, HIPAA, SOX, and GDPR.",
              icon: <CheckCircle className="h-6 w-6 text-red-600" />,
            },
            {
              title: "Threat Intelligence Integration",
              description:
                "Incorporation of global threat intelligence feeds to identify emerging threats and indicators of compromise.",
              icon: <Shield className="h-6 w-6 text-red-600" />,
            },
          ].map((item, index) => (
            <div key={index} className="bg-gray-50 p-8 rounded-lg">
              <div className="flex items-start gap-4">
                <div className="bg-red-100 p-3 rounded-full">{item.icon}</div>
                <div>
                  <h3 className="text-xl font-bold mb-2">{item.title}</h3>
                  <p className="text-gray-600">{item.description}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Use Cases Section */}
      <div className="mb-16">
        <h2 className="text-3xl font-bold mb-8 text-center">SIEM Use Cases</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[
            {
              title: "Insider Threat Detection",
              description:
                "Identify suspicious user behavior that may indicate malicious insider activity or compromised accounts.",
              icon: <AlertTriangle className="h-6 w-6 text-red-600" />,
            },
            {
              title: "Advanced Threat Detection",
              description:
                "Detect sophisticated attacks that evade traditional security controls using behavioral analytics.",
              icon: <Shield className="h-6 w-6 text-red-600" />,
            },
            {
              title: "Compliance Monitoring",
              description:
                "Continuously monitor compliance with regulatory requirements and internal security policies.",
              icon: <FileText className="h-6 w-6 text-red-600" />,
            },
            {
              title: "Data Breach Detection",
              description:
                "Identify potential data exfiltration attempts and unauthorized access to sensitive information.",
              icon: <Database className="h-6 w-6 text-red-600" />,
            },
            {
              title: "Security Operations",
              description:
                "Streamline security operations with centralized visibility and automated incident response workflows.",
              icon: <Clock className="h-6 w-6 text-red-600" />,
            },
            {
              title: "Forensic Investigation",
              description:
                "Conduct detailed forensic investigations with comprehensive historical log data and analysis tools.",
              icon: <Search className="h-6 w-6 text-red-600" />,
            },
          ].map((item, index) => (
            <div key={index} className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
              <div className="flex items-start gap-4 mb-2">
                <div className="bg-red-100 p-2 rounded-full">{item.icon}</div>
                <h3 className="text-lg font-bold">{item.title}</h3>
              </div>
              <p className="text-gray-600 pl-12">{item.description}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Implementation Process */}
      <div className="bg-gray-50 p-8 rounded-lg mb-16">
        <h2 className="text-3xl font-bold mb-8 text-center">Implementation Process</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {[
            {
              step: "1",
              title: "Assessment",
              description: "Evaluate your security monitoring needs and existing infrastructure.",
              icon: <Search className="h-6 w-6 text-red-600" />,
            },
            {
              step: "2",
              title: "Design",
              description: "Create a tailored SIEM architecture that meets your specific requirements.",
              icon: <BarChart className="h-6 w-6 text-red-600" />,
            },
            {
              step: "3",
              title: "Deployment",
              description: "Implement the solution with log source integration and custom use cases.",
              icon: <Shield className="h-6 w-6 text-red-600" />,
            },
            {
              step: "4",
              title: "Optimization",
              description: "Fine-tune detection rules and response workflows based on your environment.",
              icon: <CheckCircle className="h-6 w-6 text-red-600" />,
            },
          ].map((item, index) => (
            <div key={index} className="bg-white p-6 rounded-lg shadow-sm relative">
              <div className="absolute top-4 right-4 bg-red-600 text-white w-8 h-8 rounded-full flex items-center justify-center font-bold">
                {item.step}
              </div>
              <div className="mb-4">{item.icon}</div>
              <h3 className="text-xl font-bold mb-2">{item.title}</h3>
              <p className="text-gray-600">{item.description}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Benefits Section */}
      <div className="mb-16">
        <h2 className="text-3xl font-bold mb-8 text-center">Benefits of Our SIEM Solutions</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {[
            {
              title: "Enhanced Threat Detection",
              description:
                "Identify sophisticated threats that traditional security controls might miss with advanced analytics and correlation.",
              icon: <AlertTriangle className="h-6 w-6 text-red-600" />,
            },
            {
              title: "Reduced Response Time",
              description:
                "Decrease the time to detect and respond to security incidents with real-time alerting and automated workflows.",
              icon: <Clock className="h-6 w-6 text-red-600" />,
            },
            {
              title: "Simplified Compliance",
              description:
                "Streamline regulatory compliance with automated log collection, retention, and reporting capabilities.",
              icon: <FileText className="h-6 w-6 text-red-600" />,
            },
            {
              title: "Centralized Security Management",
              description:
                "Gain comprehensive visibility into your security posture through a single, unified platform.",
              icon: <Lock className="h-6 w-6 text-red-600" />,
            },
          ].map((item, index) => (
            <div key={index} className="bg-gray-50 p-8 rounded-lg">
              <div className="flex items-start gap-4">
                <div className="bg-red-100 p-3 rounded-full">{item.icon}</div>
                <div>
                  <h3 className="text-xl font-bold mb-2">{item.title}</h3>
                  <p className="text-gray-600">{item.description}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* CTA Section */}
      <div className="bg-red-600 text-white p-8 md:p-12 rounded-lg text-center">
        <h2 className="text-3xl font-bold mb-4">Enhance Your Security Visibility</h2>
        <p className="text-xl mb-8 max-w-3xl mx-auto">
          Gain comprehensive visibility into your security posture with our advanced SIEM solutions.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Button asChild className="bg-white text-red-600 hover:bg-gray-100">
            <Link href="/contact">Get Started</Link>
          </Button>
          <Button asChild variant="outline" className="border-white text-white hover:bg-red-700">
            <Link href="/services">Explore All Services</Link>
          </Button>
        </div>
      </div>
    </div>
  )
}

